// // import Header from "./Components/Header"
// // import Entry from "./Components/Entry"
// // export default function App() {
// //     return (
// //         <>
// //             <Header />
// //             <Entry
// //                 // (will be an object with the following properties/values)
// //                 img=
// //                 {{
// //                     src: "/src/images/WhiteTree.png",
// //                     alt: "Mount Fuji"
// //                 }}
// //                 // one curly braces for obj and one for js as it is obj 
// //                 title="Mount Fuji"
// //                 country="Japan"
// //                 googleMapsLink="https://www.google.com/maps/place/Mount+Fuji/@35.3606421,138.7170637,15z/data=!3m1!4b1!4m6!3m5!1s0x6019629a42fdc899:0xa6a1fcc916f3a4df!8m2!3d35.3606255!4d138.7273634!16zL20vMGNrczA?entry=ttu"
// //                 dates="12 Jan, 2021 - 24 Jan, 2021"
// //                 text="Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists."
// //             />
// //         </>

// //     )
// // }


// import Header from "./Components/Header"
// import Entry from "./Components/Entry"
// import data from "./data"
// export default function App() {

//     const entryElements = data.map(entry =>
//         <Entry
//             //ek js ke liye ek obj ke liye
//             // img={{
//             //     src: entry.img.src,
//             //     alt: entry.img.alt
//             // }} instead of repeting do this when ur data is same way lined up in ur file like first yh then yh here img inside src then alt

//             key={entry.id}
//             // img={entry.img}
//             // title={entry.title}
//             // country={entry.country}
//             // googleMapsLink={entry.googleMapsLink}
//             // dates={entry.dates}
//             // text={entry.text}

//             entry={entry}
//         />
//     )
//     return (
//         <>
//             <Header />
//             {entryElements}
//         </>

//     )
// }

// import Header from "./Components/Header"
// import Entry from "./Components/Entry"
// export default function App() {
//     return (
//         <>
//             <Header />
//             <Entry
//                 // (will be an object with the following properties/values)
//                 img=
//                 {{
//                     src: "/src/images/WhiteTree.png",
//                     alt: "Mount Fuji"
//                 }}
//                 title="Mount Fuji"
//                 country="Japan"
//                 googleMapsLink="https://www.google.com/maps/place/Mount+Fuji/@35.3606421,138.7170637,15z/data=!3m1!4b1!4m6!3m5!1s0x6019629a42fdc899:0xa6a1fcc916f3a4df!8m2!3d35.3606255!4d138.7273634!16zL20vMGNrczA?entry=ttu"
//                 dates="12 Jan, 2021 - 24 Jan, 2021"
//                 text="Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists."
//             />
//         </>

//     )
// }


import Header from "./Components/Header"
import Entry from "./Components/Entry"
import data from "./data"
export default function App() {

    const entryElements = data.map(entry =>
        <Entry
            key={entry.id}
            {...entry}
        />
    )
    return (
        <>
            <Header />
            {entryElements}
        </>

    )
}

// In most applications, IDs are generated by the backend (database) to ensure uniqueness.
// However, during frontend development or for static data, developers can manually create IDs and use them as keys.